.TH NAME 1
.\" NAME pvblot, SECTION 1
.SH NAME
pvblot \- pvblot
.SH SYNOPSIS
.B pvblot
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR pvblot
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
