.TH PVPYTHON 1
.SH NAME
pvpython \- pvpython
.SH SYNOPSIS
.B pvpython
.br
.SH DESCRIPTION
The
.BR pvpython
application, distributed with the ParaView application suite, is a Python client to the ParaView servers. It supports interactive execution as well as batch execution.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
