.TH NAME 1
.\" NAME smTestDriver, SECTION 1
.SH NAME
smTestDriver \- smTestDriver
.SH SYNOPSIS
.B smTestDriver
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR smTestDriver
command.

You can find information in the paraview manual page and on the
paraview web page http://www.paraview.org.

.SH AUTHOR
The Debian Scientific Computing Team
