#!/bin/bash

# The script serves for creation of paraview-python.links file

FILE_NAME='paraview-python.links_autogenerated'
echo "" > ${FILE_NAME}
for k in $(find ./tmp/usr/lib/paraview -name *Python27D.so); 
	do
	cuttedline=${k%Python27D.so*}
	cuttedline=${cuttedline#*w/}
	#echo ${cuttedline}
	
	cuttedline2=${cuttedline#*lib}
	#echo ${cuttedline2}
	
	echo usr/lib/paraview/${cuttedline}Python27D.so usr/lib/python2.7/dist-packages/${cuttedline2}Python.so >> ${FILE_NAME}
	echo usr/lib/paraview/${cuttedline}Python27D.so usr/lib/python2.7/dist-packages/${cuttedline2}Python.so 
	
	
done
